# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-08 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertest',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True, verbose_name='生日'),
        ),
    ]
