# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-08 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170808_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertest',
            name='sex',
            field=models.CharField(choices=[('man', '男'), ('woman', '女'), ('futa', '小姐姐')], default='futa', max_length=5),
        ),
    ]
