# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-08 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170808_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertest',
            name='sex',
            field=models.CharField(choices=[('man', '男'), ('woman', '女'), ('futa', '小姐姐')], max_length=10),
        ),
    ]
