# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-08 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170808_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertest',
            old_name='sex',
            new_name='user_sex',
        ),
    ]
