# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-08 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_usertest_user_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='testfuck',
            field=models.CharField(choices=[('fuck', '一'), ('you', '二')], default='you', max_length=5),
        ),
    ]
