# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-08 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_usertest_testfuck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertest',
            name='testfuck',
        ),
        migrations.AddField(
            model_name='usertest',
            name='markdown_or_not',
            field=models.CharField(choices=[('m', 'markdown'), ('c', 'ckeditor')], default='c', max_length=6, verbose_name='编辑器选择'),
        ),
    ]
