# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-08 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20170808_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertest',
            name='birthday',
        ),
    ]
