# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-08 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20170808_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertest',
            old_name='user_sex',
            new_name='sex',
        ),
    ]
